#!/bin/bash
mkdir -p results/pytorch_caffe_conv1_0_2/crashes/
cp pytorch_caffe_conv1_0_2/crashes/crashes.csv results/pytorch_caffe_conv1_0_2/crashes/
mkdir -p results/pytorch_caffe_pool1_0_2/crashes/
cp pytorch_caffe_pool1_0_2/crashes/crashes.csv results/pytorch_caffe_pool1_0_2/crashes/
mkdir -p results/pytorch_caffe_pool2_0_2/crashes/
cp pytorch_caffe_pool2_0_2/crashes/crashes.csv results/pytorch_caffe_pool2_0_2/crashes/
mkdir -p results/pytorch_caffe_relu1_0_2/crashes/
cp pytorch_caffe_relu1_0_2/crashes/crashes.csv results/pytorch_caffe_relu1_0_2/crashes/
mkdir -p results/pytorch_caffe_tanh1_0_2/crashes/
cp pytorch_caffe_tanh1_0_2/crashes/crashes.csv results/pytorch_caffe_tanh1_0_2/crashes/
mkdir -p results/pytorch_tensorflow_conv1_0_2/crashes/
cp pytorch_tensorflow_conv1_0_2/crashes/crashes.csv results/pytorch_tensorflow_conv1_0_2/crashes/
mkdir -p results/pytorch_tensorflow_conv2_0_2/crashes/
cp pytorch_tensorflow_conv2_0_2/crashes/crashes.csv results/pytorch_tensorflow_conv2_0_2/crashes/
mkdir -p results/pytorch_tensorflow_pool1_0_2/crashes/
cp pytorch_tensorflow_pool1_0_2/crashes/crashes.csv results/pytorch_tensorflow_pool1_0_2/crashes/
mkdir -p results/pytorch_tensorflow_pool2_0_2/crashes/
cp pytorch_tensorflow_pool2_0_2/crashes/crashes.csv results/pytorch_tensorflow_pool2_0_2/crashes/
mkdir -p results/pytorch_tensorflow_relu1_0_2/crashes/
cp pytorch_tensorflow_relu1_0_2/crashes/crashes.csv results/pytorch_tensorflow_relu1_0_2/crashes/
mkdir -p results/pytorch_tensorflow_tanh1_0_2/crashes/
cp pytorch_tensorflow_tanh1_0_2/crashes/crashes.csv results/pytorch_tensorflow_tanh1_0_2/crashes/
mkdir -p results/tensorflow_caffe_conv1_0_2/crashes/
cp tensorflow_caffe_conv1_0_2/crashes/crashes.csv results/tensorflow_caffe_conv1_0_2/crashes/
mkdir -p results/tensorflow_caffe_conv1_1_2/crashes/
cp tensorflow_caffe_conv1_1_2/crashes/crashes.csv results/tensorflow_caffe_conv1_1_2/crashes/
mkdir -p results/tensorflow_caffe_pool1_0_2/crashes/
cp tensorflow_caffe_pool1_0_2/crashes/crashes.csv results/tensorflow_caffe_pool1_0_2/crashes/
mkdir -p results/tensorflow_caffe_pool2_0_2/crashes/
cp tensorflow_caffe_pool2_0_2/crashes/crashes.csv results/tensorflow_caffe_pool2_0_2/crashes/
mkdir -p results/tensorflow_caffe_relu1_0_2/crashes/
cp tensorflow_caffe_relu1_0_2/crashes/crashes.csv results/tensorflow_caffe_relu1_0_2/crashes/
mkdir -p results/tensorflow_caffe_tanh1_0_2/crashes/
cp tensorflow_caffe_tanh1_0_2/crashes/crashes.csv results/tensorflow_caffe_tanh1_0_2/crashes/
mkdir -p results/tensorflow_pytorch_sigmoid1_0_2/crashes/
cp tensorflow_pytorch_sigmoid1_0_2/crashes/crashes.csv results/tensorflow_pytorch_sigmoid1_0_2/crashes/
